Replace acmetool with certbot

diff --git a/etc/dl-varnish-cloud-config.yaml b/etc/dl-varnish-cloud-config.yaml
--- a/etc/dl-varnish-cloud-config.yaml
+++ b/etc/dl-varnish-cloud-config.yaml
@@ -43,7 +43,7 @@ packages:
   - make
   - unattended-upgrades
   - hitch
-  - acmetool
+  - software-properties-common
 
 write_files:
   - path: /etc/systemd/system/varnish.service.d/customexec.conf
@@ -58,6 +58,7 @@ write_files:
     content: |
       # Creted by Hebcal cloud-config.yaml
       vcl 4.0;
+      include "/etc/varnish/letsencrypt.vcl";
       import directors;
       backend server1 {
           .host = "dl17-internal.hebcal.com";
@@ -105,27 +106,41 @@ write_files:
       }
       sub vcl_deliver {
       }
-      include "/etc/varnish/acmetool.vcl";
-  - path: /etc/default/acme-reload
+  - path: /etc/varnish/letsencrypt.vcl
     permissions: '0644'
     content: |
       # Creted by Hebcal cloud-config.yaml
-      SERVICES="$SERVICES"
-      HAPROXY_ALWAYS_GENERATE=yes
-  - path: /etc/varnish/acmetool.vcl
-    permissions: '0644'
-    content: |
-      # Creted by Hebcal cloud-config.yaml
-      backend acmetool {
+      vcl 4.0;
+      backend certbot {
          .host = "127.0.0.1";
-         .port = "402";
+         .port = "8080";
       }
       sub vcl_recv {
-          if (req.url ~ "^/.well-known/acme-challenge/") {
-              set req.backend_hint = acmetool;
-              return(pass);
+          if (req.url ~ "^/\.well-known/acme-challenge/") {
+              set req.backend_hint = certbot;
+              return(pipe);
           }
       }
+      sub vcl_pipe {
+          if (req.backend_hint == certbot) {
+              set req.http.Connection = "close";
+              return(pipe);
+          }
+      }
+  - path: /usr/local/bin/hitch-deploy-hook
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      # Full path to pre-generated Diffie Hellman Parameters file
+      dhparams=/etc/hitch/dhparams.pem
+      if [[ "${RENEWED_LINEAGE}" == "" ]]; then
+          echo "Error: missing RENEWED_LINEAGE env variable." >&2
+          exit 1
+      fi
+      umask 077
+      cat ${RENEWED_LINEAGE}/privkey.pem \
+       ${RENEWED_LINEAGE}/fullchain.pem \
+       ${dhparams} > ${RENEWED_LINEAGE}/hitch-bundle.pem
   - path: /etc/systemd/system/hitch.service.d/limits.conf
     permissions: '0644'
     content: |
@@ -142,7 +157,7 @@ write_files:
       backend        = "[127.0.0.1]:6086"
       write-proxy-v2 = on
       # List of PEM files, each with key, certificates and dhparams
-      pem-file = "/var/lib/acme/live/download.hebcal.com/haproxy"
+      pem-file = "/etc/letsencrypt/live/download.hebcal.com/hitch-bundle.pem"
 
 runcmd:
   - service netfilter-persistent flush
@@ -184,8 +199,14 @@ runcmd:
   - systemctl enable varnish.service
   - systemctl daemon-reload
   - systemctl start varnish.service
-  - mkdir -p /var/lib/acme/conf
-  - nice openssl dhparam -out /var/lib/acme/conf/dhparams 2048
-  - acmetool want download.hebcal.com --batch || exit 0
-  - acmetool reconcile --batch || exit 0
   - systemctl reload postfix.service
+  - systemctl stop hitch.service
+  - add-apt-repository universe
+  - add-apt-repository ppa:certbot/certbot
+  - apt-get update
+  - apt-get install -y certbot
+  - nice openssl dhparam 2048 | tee /etc/hitch/dhparams.pem
+  - certbot certonly -m mradwin@hebcal.com --agree-tos --non-interactive --standalone --preferred-challenges http --http-01-port 8080 -d download.hebcal.com --deploy-hook="/usr/local/bin/hitch-deploy-hook" --post-hook="systemctl reload hitch"
+  - systemctl enable certbot.timer
+  - systemctl start certbot.timer
+  - systemctl start hitch.service
