Replace acmetool with certbot for SSL certificates

diff --git a/etc/varnish-cloud-config.yaml b/etc/varnish-cloud-config.yaml
--- a/etc/varnish-cloud-config.yaml
+++ b/etc/varnish-cloud-config.yaml
@@ -48,7 +48,7 @@ packages:
   - libvarnishapi-dev
   - unattended-upgrades
   - hitch
-  - acmetool
+  - software-properties-common
 
 write_files:
   - path: /etc/systemd/system/varnish.service.d/customexec.conf
@@ -64,20 +64,41 @@ write_files:
       # Creted by Hebcal cloud-config.yaml
       SERVICES="$SERVICES"
       HAPROXY_ALWAYS_GENERATE=yes
-  - path: /etc/varnish/acmetool.vcl
+  - path: /etc/varnish/letsencrypt.vcl
     permissions: '0644'
     content: |
       # Creted by Hebcal cloud-config.yaml
-      backend acmetool {
+      vcl 4.0;
+      backend certbot {
          .host = "127.0.0.1";
-         .port = "402";
+         .port = "8080";
       }
       sub vcl_recv {
-          if (req.url ~ "^/.well-known/acme-challenge/") {
-              set req.backend_hint = acmetool;
-              return(pass);
+          if (req.url ~ "^/\.well-known/acme-challenge/") {
+              set req.backend_hint = certbot;
+              return(pipe);
           }
       }
+      sub vcl_pipe {
+          if (req.backend_hint == certbot) {
+              set req.http.Connection = "close";
+              return(pipe);
+          }
+      }
+  - path: /usr/local/bin/hitch-deploy-hook
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      # Full path to pre-generated Diffie Hellman Parameters file
+      dhparams=/etc/hitch/dhparams.pem
+      if [[ "${RENEWED_LINEAGE}" == "" ]]; then
+          echo "Error: missing RENEWED_LINEAGE env variable." >&2
+          exit 1
+      fi
+      umask 077
+      cat ${RENEWED_LINEAGE}/privkey.pem \
+       ${RENEWED_LINEAGE}/fullchain.pem \
+       ${dhparams} > ${RENEWED_LINEAGE}/hitch-bundle.pem
   - path: /etc/systemd/system/hitch.service.d/limits.conf
     permissions: '0644'
     content: |
@@ -94,7 +115,7 @@ write_files:
       backend        = "[127.0.0.1]:6086"
       write-proxy-v2 = on
       # List of PEM files, each with key, certificates and dhparams
-      pem-file = "/var/lib/acme/live/hebcal.com/haproxy"
+      pem-file = "/etc/letsencrypt/live/hebcal.com/hitch-bundle.pem"
   - path: /etc/mailname
     permissions: '0644'
     content: |
@@ -148,8 +169,13 @@ runcmd:
   - systemctl daemon-reload
   - systemctl start varnish.service
   - systemctl stop hitch.service
-  - mkdir -p /var/lib/acme/conf
-  - nice openssl dhparam -out /var/lib/acme/conf/dhparams 2048
-  - acmetool want hebcal.com www.hebcal.com --batch || exit 0
-  - acmetool reconcile --batch || exit 0
+  - add-apt-repository universe
+  - add-apt-repository ppa:certbot/certbot
+  - apt-get update
+  - apt-get install -y certbot
+  - nice openssl dhparam 2048 | tee /etc/hitch/dhparams.pem
+  - certbot certonly -m mradwin@hebcal.com --agree-tos --non-interactive --standalone --preferred-challenges http --http-01-port 8080 -d hebcal.com -d www.hebcal.com --deploy-hook="/usr/local/bin/hitch-deploy-hook" --post-hook="systemctl reload hitch"
   - systemctl reload postfix.service
+  - systemctl enable certbot.timer
+  - systemctl start certbot.timer
+  - systemctl start hitch.service
